name: "Build and Push Symfony Image"
description: "Builds a Symfony Docker image, and optionally pushes it to a Container Registry"
inputs:
  CONTAINER_REGISTRY:
    required: false
    description: "The Docker registry to push the image to"
  PUSH:
    required: false
    description: "Whether to push the image to the registry"
    default: "true"
  CACHE_FROM:
    required: false
    description: "Defines where to pull cached Docker layers from"
  CACHE_TO:
    required: false
    description: "Defines where to push cached Docker layers to"
  TAGS:
    required: false
    description: "Defines the tags to associate with the image"
  DOCKERFILE_PATH:
    required: true
    description: "The path (relative to the project's root) of the Dockerfile used to build image"
  DOCKERFILE_TARGET:
    required: true
    description: "The Docker target to use when building the image"
  IMAGE:
    required: true
    description: "The name of the Docker image to build"
  SYMFONY_ROOT:
    required: true
    description: "The path (relative to the project's root) in which the Symfony files are stored (e.g. config, src, etc)"
  BUILD_TIME_ARGS:
    required: false
    description: "(Optional) A JSON object containing a list of args and their values in key: value format"
  BUILD_TIME_SECRETS:
    required: false
    description: "(Optional) A JSON object containing a list of secrets and their values in key: value format"
  LOAD:
    required: false
    description: "Whether to load the built image into the local Docker cache"
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Prepare Docker build args
      id: build-args
      run: |
        set -e
        JSON_INPUT='${{ inputs.BUILD_TIME_ARGS }}'
        echo "args<<EOF" >> $GITHUB_OUTPUT
        echo "$JSON_INPUT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
          echo "$key=$value" >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Prepare Docker build secrets
      id: build-secrets
      run: |
        set -e
        JSON_INPUT='${{ inputs.BUILD_TIME_SECRETS }}'
        echo "secrets<<EOF" >> $GITHUB_OUTPUT
        echo "$JSON_INPUT" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS='=' read -r key value; do
          echo "::add-mask::$value"   # Mask the value from logs
          echo "$key=$value" >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT
      shell: bash

    - name: Build and push image
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
      with:
        context: .
        file: ${{ inputs.DOCKERFILE_PATH }}
        target: ${{ inputs.DOCKERFILE_TARGET }}
        build-args: |
          ${{ steps.build-args.outputs.args }}
        # During the build, several secret values don't actually matter but still need to be present (e.g. kernel-secret),
        # so we simply add dummy values here
        secrets: |
          kernel-secret=secret
          ${{ steps.build-secrets.outputs.secrets }}
        push: ${{ inputs.PUSH == 'true' }}
        cache-from: ${{ inputs.CACHE_FROM }}
        cache-to: ${{ inputs.CACHE_TO }}
        tags: ${{ inputs.TAGS }}
        load: ${{ inputs.LOAD == 'true' }}
