# Builds, tags, and pushes Symfony Docker images to an Azure Container Registry, applies Azure infrastrcuture changes, and deploys new revisions to Container Apps.
# This workflow assumes an architecture similar to the one in https://github.com/Torq-North/symfony-azure-provisioning - namely, an Azure Container Registry, an init Container App Job, a PHP Container App, and a supervisord Container App.
#
# Invoke this workflow in your project's workflow as follows:
# on:
#   push:
#     branches: [main, develop]
# jobs:
#   cd-azure-container-apps:
#     uses: Torq-North/symfony-github-actions-workflows/.github/workflows/cd-azure-container-apps.yml@v1
#     permissions:
#       contents: read
#       actions: read
#     with:
#       ENVIRONMENT: ${{ github.ref_name == 'main' && 'production' || 'test' }}
#     secrets:
#       SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
#       SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
#       BUILD_TIME_SECRETS: >
#         {
#           "my-build-secret": "${{ secrets.MY_BUILD_SECRET }}",
#           "my-other-build-secret": "${{ secrets.MY_OTHER_BUILD_SECRET }}"
#         }
#
# The GitHub Environments you use with this workflow will need the following variables:
# - AZURE_TENANT_ID
#     description: ID of the Azure tenant to deploy to
#     required: true
# - AZURE_SUBSCRIPTION_ID
#     description: ID of the Azure subscription to deploy to
#     required: true
# - RESOURCE_GROUP
#     description: Name of the Azure Resource Group to deploy to
#     required: true
# - CONTAINER_REGISTRY
#     description: Name of the Azure Container Registry to deploy to. This should be the fully qualified name - e.g. myregistry.azurecr.io
#     required: true
# - CONTAINER_REGISTRY_FIREWALL
#     description: True if the Azure Container Registry has a network firewall that needs to be bypassed before pushing images.
#     required: false
#     default: false
# - INIT_IMAGE
#     description: Name of the init Docker image to push to the registry
#     required: false
#     default value: init
# - INIT_CONTAINER_NAME
#     description: Name of the container inside the init Container App Job
#     required: false
#     default value: init
# - INIT_CONTAINER_APP_JOB
#     description: Name of the init Container App Job
#     required: true
# - PHP_IMAGE
#     description: Name of the PHP Docker image to push to the registry
#     required: false
#     default value: php
# - PHP_CONTAINER_APP
#     description: Name of the PHP Container App
#     required: true
# - SUPERVISORD_IMAGE
#     description: Name of the supervisord Docker image to push to the registry
#     required: false
#     default value: supervisord
# - SUPERVISORD_CONTAINER_APP
#     description: Name of the supervisord Container App
#     required: true
# - AZURE_PARAMETERS_FILE
#     description: Name of the Azure parameters file to use to deploy infrastructure changes. Will be assumed to be located in the directory defined by the AZURE_DIRECTORY input.
#     required: false
#     default: parameters.ENVIRONMENT.json
#

name: Azure Container Apps Deployment

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
        description: "The GitHub Environment in which to run the workflow"
      RUNNER:
        required: false
        type: string
        description: Optional self-hosted runner for this workflow (see https://github.com/Torq-North/symfony-github-actions-workflows#self-hosted-runners)
      PROJECT_REPOSITORY:
        required: false
        type: string
        default: ${{ github.repository }}
        description: "The repository in which the Symfony project is located, in owner/repo format. If not provided, the value of github.repository will be used"
      PROJECT_REPOSITORY_REF:
        required: false
        type: string
        default: ${{ github.ref }}
        description: "The branch or tag of the repository to use. If not provided, the branch that this workflow was called from will be used"
      SKIP_LINTING:
        required: false
        type: boolean
        default: false
        description: "Whether linting should be skipped"
      BUILD_TIME_ARGS:
        required: false
        type: string
        default: "{}"
        description: "A JSON object containing Docker build-time args in key: value format"
      NPM_BUILD:
        required: false
        type: boolean
        default: true
        description: "Whether an NPM build should be run prior to building the PHP image"
      NPM_RUN_CMD:
        required: false
        type: string
        default: build
        description: "The NPM command that should be run prior to building the PHP image"
      NPM_SPA:
        required: false
        type: boolean
        default: true
        description: "Whether the NPM build results in a single-page application"
      SPA_TWIG:
        required: false
        type: string
        default: "default/default.html.twig"
        description: "The path to the Twig file where the result of the NPM single-page application build should be copied"
      FRONTEND_ROOT:
        required: false
        type: string
        default: "frontend"
        description: "The path (relative to the project's root) where frontend files are stored"
      SUBMODULES:
        required: false
        type: boolean
        default: false
        description: "Whether to clone submodules when cloning the project repository"
      SYMFONY_ROOT:
        required: false
        type: string
        default: "."
        description: "The path (relative to the project's root) in which the Symfony files are stored (e.g. config, src, etc)"
      INIT_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the init image"
      INIT_DOCKER_TARGET:
        required: false
        type: string
        default: "init"
        description: "The Docker target to use when building the init image"
      PHP_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the PHP image"
      PHP_DOCKER_TARGET:
        required: false
        type: string
        default: "php"
        description: "The Docker target to use when building the PHP image"
      SUPERVISORD_DOCKERFILE:
        required: false
        type: string
        default: ".docker/Dockerfile"
        description: "The path (relative to the project's root) of the Dockerfile used to build the supervisord image"
      SUPERVISORD_TARGET:
        required: false
        type: string
        default: "supervisord"
        description: "The Docker target to use when building the supervisord image"
      AZURE_DIRECTORY:
        required: false
        type: string
        default: ".azure"
        description: "The path (relative to the project's root) of the directory containing the project's Azure parameter files"
      AZURE_IMAGE_TAG:
        required: false
        type: string
        default: "0"
        description: "Tag to use when pulling the TORQ Azure provisioning image (https://github.com/Torq-North/symfony-azure-provisioning)"
      AZURE_SKIP_DB_DEPLOY:
        required: false
        type: boolean
        default: false
        description: "Whether database deployment steps should be skipped when applying Azure infrastructure changes"
      PROVISION_SUPERVISORD:
        required: false
        type: boolean
        default: false
        description: "Whether the supervisord image and Container App should be provisioned and deployed to. If false, only the init and PHP images and Container Apps will be handled."
      GITHUB_APP_CHECKOUT:
        required: false
        type: boolean
        default: false
        description: "Whether to use a GitHub App token for checking out the project repository and submodules"

    secrets:
      SERVICE_PRINCIPAL_ID:
        required: true
        description: The ID of the Service Principal in Azure that will be used to deploy. The Service Principal must have permission to push images to the Container Registry and to deploy new revisions to the init, PHP and supervisord Container Apps.
      SERVICE_PRINCIPAL_PASSWORD:
        required: true
        description: The password for the Service Principal in Azure
      BUILD_TIME_SECRETS:
        required: false
        description: A JSON object of secrets required at build-time (see above for example format)
      RECAPTCHA_CLIENT_KEY:
        required: false
        description: (Optional) A client key used when building NPM frontends that require ReCAPTCHA
      SLACK_WORKFLOW_STATUS_WEBHOOK_URL:
        required: false
        description: (Optional) Slack webhook URL to send workflow results to
      GITHUB_APP_ID:
        required: false
        description: The ID of the GitHub App used to generate a token for checking out the project repository and submodules
      GITHUB_APP_PRIVATE_KEY:
        required: false
        description: The private key of the GitHub App used to generate a token for checking out the project repository and submodules

jobs:
  build-and-push-images:
    name: Build and push Symfony Docker images
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1.0.4
        with:
          repository-name: Torq-North/symfony-github-actions-workflows
          file-name: cd-azure-container-apps.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Torq-North/symfony-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Check out project repository and submodules
        uses: ./reusable-workflow/.github/actions/checkout
        with:
          PROJECT_REPOSITORY: ${{ inputs.PROJECT_REPOSITORY }}
          PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
          SUBMODULES: ${{ inputs.SUBMODULES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_CHECKOUT: ${{ inputs.GITHUB_APP_CHECKOUT }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Install tools for workflows/actions
        uses: ./reusable-workflow/.github/actions/setup-tools

      - name: Lint files
        if: ${{ inputs.SKIP_LINTING == false }}
        uses: ./reusable-workflow/.github/actions/lint

      - name: Log in to Azure
        uses: ./reusable-workflow/.github/actions/azure-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Add exception to Azure Container Registry firewall, if one is in place
        if: ${{ vars.CONTAINER_REGISTRY_FIREWALL || false }}
        run: |
          az acr network-rule add -n ${{ vars.CONTAINER_REGISTRY }} --ip-address $(curl ipinfo.io/ip)
          # Sleep for a few seconds to allow network rules to propagate
          sleep 60

      - name: Set up Docker
        uses: ./reusable-workflow/.github/actions/setup-docker
        with:
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_REGISTRY_USERNAME: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          CONTAINER_REGISTRY_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}

      - name: Apply Azure infrastructure changes
        uses: ./reusable-workflow/.github/actions/azure-apply-infra-changes
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.AZURE_TENANT_ID }}
          AZURE_DIRECTORY: ${{ inputs.AZURE_DIRECTORY }}
          AZURE_IMAGE_TAG: ${{ inputs.AZURE_IMAGE_TAG }}
          AZURE_PARAMETERS_FILE: ${{ vars.AZURE_PARAMETERS_FILE }}
          AZURE_SKIP_DB_DEPLOY: ${{ inputs.AZURE_SKIP_DB_DEPLOY }}

      - name: Build frontend
        if: ${{ inputs.NPM_BUILD == true }}
        uses: ./reusable-workflow/.github/actions/build-frontend
        with:
          SYMFONY_ROOT: ${{ inputs.SYMFONY_ROOT }}
          FRONTEND_ROOT: ${{ inputs.FRONTEND_ROOT }}
          NPM_RUN_CMD: ${{ inputs.NPM_RUN_CMD }}
          NPM_SPA: ${{ inputs.NPM_SPA }}
          SPA_TWIG: ${{ inputs.SPA_TWIG }}
          RECAPTCHA_CLIENT_KEY: ${{ secrets.RECAPTCHA_CLIENT_KEY }}

      - name: Build and push init image
        uses: ./reusable-workflow/.github/actions/build-and-push-symfony-image
        with:
          DOCKERFILE_PATH: ${{ inputs.INIT_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.INIT_DOCKER_TARGET }}
          SYMFONY_ROOT: ${{ inputs.SYMFONY_ROOT }}
          BUILD_TIME_SECRETS: ${{secrets.BUILD_TIME_SECRETS }}
          CACHE_FROM: type=gha
          CACHE_TO: type=gha,mode=min
          TAGS: |
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.INIT_IMAGE || 'init' }}:latest,
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.INIT_IMAGE || 'init' }}:${{ github.run_id }}

      - name: Build and push PHP image
        uses: ./reusable-workflow/.github/actions/build-and-push-symfony-image
        with:
          DOCKERFILE_PATH: ${{ inputs.PHP_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.PHP_DOCKER_TARGET }}
          SYMFONY_ROOT: ${{ inputs.SYMFONY_ROOT }}
          BUILD_TIME_SECRETS: ${{secrets.BUILD_TIME_SECRETS }}
          TAGS: |
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.PHP_IMAGE || 'php' }}:latest,
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.PHP_IMAGE || 'php' }}:${{ github.run_id }}

      - name: Build and push supervisord image
        uses: ./reusable-workflow/.github/actions/build-and-push-symfony-image
        if: ${{ inputs.PROVISION_SUPERVISORD }}
        with:
          DOCKERFILE_PATH: ${{ inputs.SUPERVISORD_DOCKERFILE }}
          DOCKERFILE_TARGET: ${{ inputs.SUPERVISORD_TARGET }}
          SYMFONY_ROOT: ${{ inputs.SYMFONY_ROOT }}
          BUILD_TIME_SECRETS: ${{secrets.BUILD_TIME_SECRETS }}
          TAGS: |
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.SUPERVISORD_IMAGE || 'supervisord' }}:latest,
            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.SUPERVISORD_IMAGE || 'supervisord' }}:${{ github.run_id }}

      - name: Remove exception from Azure Container Registry firewall, if one is in place
        if: always()
        run: |
          if [[ ${{ vars.CONTAINER_REGISTRY_FIREWALL || false }} == "true" ]]; then
            echo "Removing exception for this runner's IP from Container Registry firewall..."
            az acr network-rule remove -n ${{ vars.CONTAINER_REGISTRY }} --ip-address $(curl ipinfo.io/ip)
          else
            echo "Container Registry has no firewall in place, so nothing to do"
          fi

  deploy-and-run-init:
    name: Deploy and run init Container App Job
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - build-and-push-images
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1.0.4
        with:
          repository-name: Torq-North/symfony-github-actions-workflows
          file-name: cd-azure-container-apps.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Torq-North/symfony-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Check out project repository and submodules
        uses: ./reusable-workflow/.github/actions/checkout
        with:
          PROJECT_REPOSITORY: ${{ inputs.PROJECT_REPOSITORY }}
          PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
          SUBMODULES: ${{ inputs.SUBMODULES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_CHECKOUT: ${{ inputs.GITHUB_APP_CHECKOUT }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Install tools for workflows/actions
        uses: ./reusable-workflow/.github/actions/setup-tools

      - name: Log in to Azure
        uses: ./reusable-workflow/.github/actions/azure-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy and run init Container App Job
        uses: ./reusable-workflow/.github/actions/azure-container-apps-deploy-and-run-init
        timeout-minutes: 15 # as there is a (low to zero) chance of an infinite loop in this action, set a timeout just in case
        with:
          INIT_IMAGE: ${{ vars.INIT_IMAGE || 'init' }}
          INIT_CONTAINER_NAME: ${{ vars.INIT_CONTAINER_NAME || 'init' }}
          INIT_CONTAINER_APP_JOB: ${{ vars.INIT_CONTAINER_APP_JOB }}
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}

  deploy-php-container-app-revision:
    name: Deploy new revision of PHP Container App
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - deploy-and-run-init
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1.0.4
        with:
          repository-name: Torq-North/symfony-github-actions-workflows
          file-name: cd-azure-container-apps.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Torq-North/symfony-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Check out project repository and submodules
        uses: ./reusable-workflow/.github/actions/checkout
        with:
          PROJECT_REPOSITORY: ${{ inputs.PROJECT_REPOSITORY }}
          PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
          SUBMODULES: ${{ inputs.SUBMODULES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_CHECKOUT: ${{ inputs.GITHUB_APP_CHECKOUT }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Install tools for workflows/actions
        uses: ./reusable-workflow/.github/actions/setup-tools

      - name: Log in to Azure
        uses: ./reusable-workflow/.github/actions/azure-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy new revision of Container App
        uses: ./reusable-workflow/.github/actions/azure-container-apps-deploy-revision
        with:
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_APP: ${{ vars.PHP_CONTAINER_APP }}
          IMAGE: ${{ vars.PHP_IMAGE || 'php' }}
          MULTI_REVISION: "true"

  # TODO using a matrix to de-duplicate these two jobs does not seem possible as we are using the "vars" context, which matrices seem to be unable to access (inputs appear empty)
  deploy-supervisord-container-app-revision:
    name: Deploy new revision of supervisord Container App
    if: ${{ inputs.PROVISION_SUPERVISORD }}
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    needs:
      - deploy-and-run-init
    steps:
      - name: Get workflow version
        id: workflow-version
        uses: canonical/get-workflow-version-action@ba22d0abdc1eda539aa3ac81af1cfee160b10714 # v1.0.4
        with:
          repository-name: Torq-North/symfony-github-actions-workflows
          file-name: cd-azure-container-apps.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout workflow repository to use composite actions
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: Torq-North/symfony-github-actions-workflows
          ref: ${{ steps.workflow-version.outputs.sha }}
          path: reusable-workflow
          fetch-depth: 1

      - name: Check out project repository and submodules
        uses: ./reusable-workflow/.github/actions/checkout
        with:
          PROJECT_REPOSITORY: ${{ inputs.PROJECT_REPOSITORY }}
          PROJECT_REPOSITORY_REF: ${{ inputs.PROJECT_REPOSITORY_REF }}
          SUBMODULES: ${{ inputs.SUBMODULES }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_APP_CHECKOUT: ${{ inputs.GITHUB_APP_CHECKOUT }}
          GITHUB_APP_ID: ${{ secrets.GITHUB_APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Install tools for workflows/actions
        uses: ./reusable-workflow/.github/actions/setup-tools

      - name: Log in to Azure
        uses: ./reusable-workflow/.github/actions/azure-login
        with:
          SERVICE_PRINCIPAL_ID: ${{ secrets.SERVICE_PRINCIPAL_ID }}
          SERVICE_PRINCIPAL_PASSWORD: ${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}
          TENANT: ${{ vars.AZURE_TENANT_ID }}
          SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy new revision of Container App
        uses: ./reusable-workflow/.github/actions/azure-container-apps-deploy-revision
        with:
          RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
          CONTAINER_REGISTRY: ${{ vars.CONTAINER_REGISTRY }}
          CONTAINER_APP: ${{ vars.SUPERVISORD_CONTAINER_APP }}
          IMAGE: ${{ vars.SUPERVISORD_IMAGE || 'supervisord' }}

  workflow-failure-notification:
    name: Send workflow failure notification to Slack channel
    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
    environment: ${{ inputs.ENVIRONMENT }}
    if: failure()
    needs:
      - deploy-and-run-init
      - deploy-php-container-app-revision
      - deploy-supervisord-container-app-revision
    steps:
      - id: check-webhook-url
        # Hacky workaround to get around the fact that we cannot reference secrets in a conditional
        run: |
          if [ "${{ secrets.SLACK_WORKFLOW_STATUS_WEBHOOK_URL }}" != '' ]; then
            echo "Slack webhook URL is defined"
            echo "slackWebhookDefined=true" >> $GITHUB_OUTPUT;
          else
            echo "Slack webhook URL is not defined"
            echo "slackWebhookDefined=false" >> $GITHUB_OUTPUT;
          fi

      - name: Send job status to Slack
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        if: steps.check-webhook-url.outputs.slackWebhookDefined == 'true'
        with:
          webhook: ${{ secrets.SLACK_WORKFLOW_STATUS_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub deployment failure*"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*Azure Container Apps deployment to ${{ inputs.ENVIRONMENT }} for ${{ github.repository }}* failed :x:\n\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
